-- Your SQL goes here
CREATE TABLE IF NOT EXISTS vcards (
    uuid TEXT NOT NULL UNIQUE,
	email TEXT,
	firstname TEXT,
	lastname TEXT,
	middlename TEXT,
	organization TEXT,
	w_phone TEXT,
	title TEXT,
	url TEXT,
	workurl TEXT,
	note TEXT,
	nickname TEXT,
	prefix TEXT,
	suffix TEXT,
	gender TEXT,
	role TEXT,
	h_phone TEXT,
	c_phone TEXT,
	p_phone TEXT,
	h_fax TEXT,
	w_fax TEXT,
	h_email TEXT,
	w_email TEXT,
	alias TEXT,
	h_address TEXT,
	w_address TEXT,
	PRIMARY KEY (uuid)
) WITHOUT ROWID